# Autogenerated wrapper script for gfm_jll for x86_64-linux-gnu
export gfm, libgfm, libgfm_extensions

JLLWrappers.@generate_wrapper_header("gfm")
JLLWrappers.@declare_library_product(libgfm, "libcmark-gfm.so.0.29.0.gfm.6")
JLLWrappers.@declare_library_product(libgfm_extensions, "libcmark-gfm-extensions.so.0.29.0.gfm.6")
JLLWrappers.@declare_executable_product(gfm)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgfm,
        "lib/libcmark-gfm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgfm_extensions,
        "lib/libcmark-gfm-extensions.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        gfm,
        "bin/cmark-gfm",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
